# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'para_yaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from yazi_ile_para import *
import locale
locale.setlocale(locale.LC_ALL, '')
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Para İfade")
        Dialog.resize(376, 263)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ico/Clip.ico"),   QtGui.QIcon.Normal, QtGui.QIcon.Off )
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        """self.lineEdit.focusOutEvent(self.click())"""

        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 361, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.clicked.connect(self.click)

        self.pushButton.setGeometry(QtCore.QRect(270, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Para İfadesi Oluşturma"))
        self.lineEdit.setText(_translate("Dialog", "1254635,23"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "365856"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Yalnız Bir Milyon İki Yüz Elli Dört Bin Altı Yüz Otuz Beş Türk Lirası ve Yirmi Üç Kuruştur."))
        self.pushButton.setText(_translate("Dialog", "Oluştur"))

    def click(self):
        pr= self.lineEdit.text()
        pr = pr.replace(" ₺", "")
        p1 = len(pr) - 2
        p2 = len(pr) - 3
        if pr[p1] == ".":
            pr = pr[0:p1] + "," + pr[p1 + 1]
        elif pr[p2] == ".":
            pr = pr[0:p2] + "," + pr[p2 + 1:len(pr)]
        pr = pr.replace(".", "", 4)
        self.lineEdit.setText(pr)
        pr=para_yazi_ile(pr)
        self.textEdit.setText(pr)
        pr=self.lineEdit.text()
        pr = pr.replace(",", ".")
        pr = float(pr)
        pr = str(locale.currency(pr, grouping=True))
        pr=pr.replace("?","₺")
        self.lineEdit.setText(pr)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
